export const chartTypeCatalog = [
  { id: 'annotation', name: 'Annotation chart', quickApi: 'annotation', mark: 'annotation' },
  {
    id: 'annotated-timeline',
    name: 'Annotated timeline',
    quickApi: 'annotatedTimeline',
    mark: 'annotation',
  },
  { id: 'area', name: 'Area chart', quickApi: 'area', mark: 'area' },
  { id: 'bar', name: 'Bar chart', quickApi: 'horizontalBar', mark: 'bar' },
  { id: 'bubble', name: 'Bubble chart', quickApi: 'bubble', mark: 'bubble' },
  { id: 'calendar', name: 'Calendar chart', quickApi: 'calendar', mark: 'calendar' },
  { id: 'candlestick', name: 'Candlestick chart', quickApi: 'candlestick', mark: 'candlestick' },
  { id: 'column', name: 'Column chart', quickApi: 'column', mark: 'bar' },
  { id: 'combo', name: 'Combo chart', quickApi: 'combo', mark: 'multiple' },
  { id: 'diff', name: 'Diff chart', quickApi: 'diff', mark: 'diff' },
  { id: 'donut', name: 'Donut chart', quickApi: 'donut', mark: 'pie' },
  { id: 'gantt', name: 'Gantt chart', quickApi: 'gantt', mark: 'gantt' },
  { id: 'gauge', name: 'Gauge chart', quickApi: 'gauge', mark: 'gauge' },
  { id: 'geo', name: 'GeoChart', quickApi: 'geo', mark: 'geo' },
  { id: 'histogram', name: 'Histogram', quickApi: 'histogram', mark: 'histogram' },
  { id: 'intervals', name: 'Intervals', quickApi: 'intervals', mark: 'interval' },
  { id: 'line', name: 'Line chart', quickApi: 'line', mark: 'line' },
  { id: 'map', name: 'Map', quickApi: 'map', mark: 'map' },
  { id: 'motion', name: 'Motion chart', quickApi: 'motion', mark: 'motion' },
  { id: 'org', name: 'Organization chart', quickApi: 'org', mark: 'org' },
  { id: 'pie', name: 'Pie chart', quickApi: 'pie', mark: 'pie' },
  { id: 'sankey', name: 'Sankey diagram', quickApi: 'sankey', mark: 'sankey' },
  { id: 'scatter', name: 'Scatter chart', quickApi: 'scatter', mark: 'point' },
  { id: 'stepped-area', name: 'Stepped area chart', quickApi: 'steppedArea', mark: 'stepped-area' },
  { id: 'table', name: 'Table chart', quickApi: 'table', mark: 'table' },
  { id: 'timeline', name: 'Timeline', quickApi: 'timeline', mark: 'timeline' },
  { id: 'treemap', name: 'Tree map', quickApi: 'treemap', mark: 'treemap' },
  { id: 'trendline', name: 'Trendline', quickApi: 'trendline', mark: 'trendline' },
  { id: 'vega', name: 'VegaChart', quickApi: 'vegaChart', mark: 'vega' },
  { id: 'waterfall', name: 'Waterfall chart', quickApi: 'waterfall', mark: 'waterfall' },
  { id: 'word-tree', name: 'Word tree', quickApi: 'wordTree', mark: 'word-tree' },
] as const;

export type ChartTypeId = (typeof chartTypeCatalog)[number]['id'];
