export type SeriesChartCategory =
  | 'cartesian'
  | 'distribution'
  | 'flow'
  | 'financial'
  | 'indicator'
  | 'map'
  | 'radial'
  | 'relationship';

export interface SeriesChartTypeEntry {
  readonly id: string;
  readonly name: string;
  readonly quickApi: string;
  readonly mark: string;
  readonly category: SeriesChartCategory;
  readonly canonicalFamily: string;
}

const entry = (
  id: string,
  name: string,
  quickApi: string,
  mark: string,
  category: SeriesChartCategory,
  canonicalFamily = id,
): SeriesChartTypeEntry => ({ id, name, quickApi, mark, category, canonicalFamily });

/**
 * Specialized series that extend the established and advanced catalogs.
 * Existing families are represented once and reused through canonical aliases.
 */
export const seriesChartTypeCatalog = [
  entry('arc-diagram', 'Arc diagram', 'arcDiagram', 'arc-diagram', 'relationship'),
  entry('area-range', 'Area range chart', 'areaRange', 'range', 'cartesian'),
  entry('area-spline', 'Smooth area chart', 'areaSpline', 'smooth', 'cartesian'),
  entry('area-spline-range', 'Smooth area range chart', 'areaSplineRange', 'range', 'cartesian'),
  entry('bell-curve', 'Bell curve', 'bellCurve', 'distribution', 'distribution'),
  entry('bullet', 'Bullet chart', 'bullet', 'bullet', 'cartesian'),
  entry('column-pyramid', 'Column pyramid chart', 'columnPyramid', 'pyramid', 'cartesian'),
  entry('column-range', 'Column range chart', 'columnRange', 'range', 'cartesian'),
  entry('contour', 'Contour chart', 'contour', 'contour', 'distribution'),
  entry('cylinder', 'Cylinder chart', 'cylinder', 'cylinder', 'cartesian'),
  entry(
    'dependency-wheel',
    'Dependency wheel',
    'dependencyWheel',
    'chord',
    'relationship',
    'chord',
  ),
  entry('dumbbell', 'Dumbbell chart', 'dumbbell', 'range', 'cartesian'),
  entry('error-bar', 'Error bar chart', 'errorBar', 'interval', 'cartesian', 'intervals'),
  entry('funnel-3d', 'Depth funnel chart', 'funnel3d', 'pyramid', 'radial'),
  entry('item', 'Item chart', 'itemChart', 'item', 'radial'),
  entry('lollipop', 'Lollipop chart', 'lollipop', 'lollipop', 'cartesian'),
  entry('network-graph', 'Network graph', 'networkGraph', 'graph', 'relationship', 'graph'),
  entry(
    'organization-network',
    'Organization network',
    'organizationNetwork',
    'org',
    'relationship',
    'org',
  ),
  entry('packed-bubble', 'Packed bubble chart', 'packedBubble', 'packed-bubble', 'relationship'),
  entry('pareto', 'Pareto chart', 'pareto', 'pareto', 'distribution'),
  entry(
    'pictorial-column',
    'Pictorial column chart',
    'pictorialColumn',
    'pictorial-bar',
    'cartesian',
    'pictorial-bar',
  ),
  entry('polygon', 'Polygon chart', 'polygon', 'polygon', 'cartesian'),
  entry('pyramid', 'Pyramid chart', 'pyramid', 'pyramid', 'radial'),
  entry('pyramid-3d', 'Depth pyramid chart', 'pyramid3d', 'pyramid', 'radial', 'pyramid'),
  entry('scatter-3d', 'Three-axis scatter chart', 'scatter3d', 'scatter-3d', 'cartesian'),
  entry('solid-gauge', 'Solid gauge', 'solidGauge', 'solid-gauge', 'radial'),
  entry('spline', 'Spline chart', 'spline', 'smooth', 'cartesian'),
  entry('streamgraph', 'Streamgraph', 'streamgraph', 'theme-river', 'distribution', 'theme-river'),
  entry('tile-map', 'Tile map', 'tileMap', 'tilemap', 'map'),
  entry('tree-graph', 'Tree graph', 'treeGraph', 'tree', 'relationship', 'tree'),
  entry('variable-pie', 'Variable radius pie chart', 'variablePie', 'variable-pie', 'radial'),
  entry('variable-width', 'Variable width column chart', 'variableWidth', 'variwide', 'cartesian'),
  entry('vector', 'Vector field chart', 'vector', 'vector', 'cartesian'),
  entry('venn', 'Venn diagram', 'venn', 'venn', 'relationship'),
  entry('wind-barb', 'Wind barb chart', 'windBarb', 'wind-barb', 'cartesian'),
  entry('word-cloud', 'Word cloud', 'wordCloud', 'word-cloud', 'relationship'),
  entry('x-range', 'Horizontal range chart', 'xRange', 'timeline', 'cartesian', 'timeline'),

  entry('acceleration-bands', 'Acceleration bands', 'accelerationBands', 'indicator', 'indicator'),
  entry('awesome-oscillator', 'Awesome oscillator', 'awesomeOscillator', 'indicator', 'indicator'),
  entry(
    'absolute-price-oscillator',
    'Absolute price oscillator',
    'absolutePriceOscillator',
    'indicator',
    'indicator',
  ),
  entry('aroon', 'Aroon indicator', 'aroon', 'indicator', 'indicator'),
  entry('aroon-oscillator', 'Aroon oscillator', 'aroonOscillator', 'indicator', 'indicator'),
  entry('average-true-range', 'Average true range', 'averageTrueRange', 'indicator', 'indicator'),
  entry('volatility-bands', 'Volatility bands', 'volatilityBands', 'indicator', 'indicator'),
  entry(
    'commodity-channel-index',
    'Commodity channel index',
    'commodityChannelIndex',
    'indicator',
    'indicator',
  ),
  entry('chaikin-oscillator', 'Chaikin oscillator', 'chaikinOscillator', 'indicator', 'indicator'),
  entry('chaikin-money-flow', 'Chaikin money flow', 'chaikinMoneyFlow', 'indicator', 'indicator'),
  entry(
    'chande-momentum-oscillator',
    'Chande momentum oscillator',
    'chandeMomentumOscillator',
    'indicator',
    'indicator',
  ),
  entry(
    'double-exponential-average',
    'Double exponential moving average',
    'doubleExponentialMovingAverage',
    'indicator',
    'indicator',
  ),
  entry('disparity-index', 'Disparity index', 'disparityIndex', 'indicator', 'indicator'),
  entry(
    'directional-movement-index',
    'Directional movement index',
    'directionalMovementIndex',
    'indicator',
    'indicator',
  ),
  entry(
    'detrended-price-oscillator',
    'Detrended price oscillator',
    'detrendedPriceOscillator',
    'indicator',
    'indicator',
  ),
  entry(
    'exponential-moving-average',
    'Exponential moving average',
    'exponentialMovingAverage',
    'indicator',
    'indicator',
  ),
  entry('event-flags', 'Event flags', 'eventFlags', 'flags', 'financial'),
  entry('heikin-ashi', 'Heikin-Ashi chart', 'heikinAshi', 'financial', 'financial'),
  entry('high-low-close', 'High-low-close chart', 'highLowClose', 'financial', 'financial'),
  entry(
    'hollow-candlestick',
    'Hollow candlestick chart',
    'hollowCandlestick',
    'financial',
    'financial',
  ),
  entry('ichimoku-cloud', 'Ichimoku cloud', 'ichimokuCloud', 'indicator', 'indicator'),
  entry('keltner-channels', 'Keltner channels', 'keltnerChannels', 'indicator', 'indicator'),
  entry('klinger-oscillator', 'Klinger oscillator', 'klingerOscillator', 'indicator', 'indicator'),
  entry('linear-regression', 'Linear regression', 'linearRegression', 'indicator', 'indicator'),
  entry(
    'linear-regression-angle',
    'Linear regression angle',
    'linearRegressionAngle',
    'indicator',
    'indicator',
  ),
  entry(
    'linear-regression-intercept',
    'Linear regression intercept',
    'linearRegressionIntercept',
    'indicator',
    'indicator',
  ),
  entry(
    'linear-regression-slope',
    'Linear regression slope',
    'linearRegressionSlope',
    'indicator',
    'indicator',
  ),
  entry(
    'moving-average-convergence-divergence',
    'Moving average convergence divergence',
    'movingAverageConvergenceDivergence',
    'indicator',
    'indicator',
  ),
  entry('money-flow-index', 'Money flow index', 'moneyFlowIndex', 'indicator', 'indicator'),
  entry('momentum', 'Momentum indicator', 'momentumIndicator', 'indicator', 'indicator'),
  entry(
    'normalized-average-true-range',
    'Normalized average true range',
    'normalizedAverageTrueRange',
    'indicator',
    'indicator',
  ),
  entry('on-balance-volume', 'On-balance volume', 'onBalanceVolume', 'indicator', 'indicator'),
  entry(
    'open-high-low-close',
    'Open-high-low-close chart',
    'openHighLowClose',
    'financial',
    'financial',
  ),
  entry('price-channel', 'Price channel', 'priceChannel', 'indicator', 'indicator'),
  entry('pivot-points', 'Pivot points', 'pivotPoints', 'indicator', 'indicator'),
  entry(
    'point-and-figure',
    'Point and figure chart',
    'pointAndFigure',
    'point-figure',
    'financial',
  ),
  entry(
    'percentage-price-oscillator',
    'Percentage price oscillator',
    'percentagePriceOscillator',
    'indicator',
    'indicator',
  ),
  entry('price-envelopes', 'Price envelopes', 'priceEnvelopes', 'indicator', 'indicator'),
  entry(
    'parabolic-stop-and-reverse',
    'Parabolic stop and reverse',
    'parabolicStopAndReverse',
    'indicator',
    'indicator',
  ),
  entry('renko', 'Renko chart', 'renko', 'renko', 'financial'),
  entry('rate-of-change', 'Rate of change', 'rateOfChange', 'indicator', 'indicator'),
  entry(
    'relative-strength-index',
    'Relative strength index',
    'relativeStrengthIndex',
    'indicator',
    'indicator',
  ),
  entry(
    'slow-stochastic',
    'Slow stochastic oscillator',
    'slowStochastic',
    'indicator',
    'indicator',
  ),
  entry(
    'simple-moving-average',
    'Simple moving average',
    'simpleMovingAverage',
    'indicator',
    'indicator',
  ),
  entry('stochastic', 'Stochastic oscillator', 'stochastic', 'indicator', 'indicator'),
  entry('supertrend', 'Supertrend', 'supertrend', 'indicator', 'indicator'),
  entry(
    'triple-exponential-average',
    'Triple exponential moving average',
    'tripleExponentialMovingAverage',
    'indicator',
    'indicator',
  ),
  entry(
    'triple-exponential-oscillator',
    'Triple exponential average oscillator',
    'tripleExponentialAverageOscillator',
    'indicator',
    'indicator',
  ),
  entry('volume-by-price', 'Volume by price', 'volumeByPrice', 'volume-profile', 'financial'),
  entry(
    'volume-weighted-average-price',
    'Volume weighted average price',
    'volumeWeightedAveragePrice',
    'indicator',
    'indicator',
  ),
  entry('williams-range', 'Williams range', 'williamsRange', 'indicator', 'indicator'),
  entry(
    'weighted-moving-average',
    'Weighted moving average',
    'weightedMovingAverage',
    'indicator',
    'indicator',
  ),
  entry('zigzag', 'Zigzag indicator', 'zigzag', 'indicator', 'indicator'),

  entry('flow-map', 'Flow map', 'flowMap', 'geo-flow', 'map'),
  entry('geo-heatmap', 'Geographic heatmap', 'geoHeatmap', 'geo-heatmap', 'map'),
  entry('map-bubble', 'Map bubble chart', 'mapBubble', 'map', 'map', 'map'),
  entry('map-line', 'Map line chart', 'mapLine', 'geo-line', 'map'),
  entry('map-point', 'Map point chart', 'mapPoint', 'map', 'map', 'map'),
  entry('tiled-map', 'Tiled map', 'tiledMap', 'tiled-map', 'map'),
] as const;

export type SeriesChartTypeId = (typeof seriesChartTypeCatalog)[number]['id'];

export interface SeriesCompatibilityEntry {
  readonly identifier: string;
  readonly familyId: string;
}

const compatibility = (identifier: string, familyId: string): SeriesCompatibilityEntry => ({
  identifier,
  familyId,
});

/** Public series identifiers and the single catalog family that implements each one. */
export const seriesCompatibilityCatalog = [
  compatibility('abands', 'acceleration-bands'),
  compatibility('ao', 'awesome-oscillator'),
  compatibility('apo', 'absolute-price-oscillator'),
  compatibility('arcdiagram', 'arc-diagram'),
  compatibility('area', 'area'),
  compatibility('arearange', 'area-range'),
  compatibility('areaspline', 'area-spline'),
  compatibility('areasplinerange', 'area-spline-range'),
  compatibility('aroon', 'aroon'),
  compatibility('aroonoscillator', 'aroon-oscillator'),
  compatibility('atr', 'average-true-range'),
  compatibility('bar', 'bar'),
  compatibility('bb', 'volatility-bands'),
  compatibility('bellcurve', 'bell-curve'),
  compatibility('boxplot', 'boxplot'),
  compatibility('bubble', 'bubble'),
  compatibility('bullet', 'bullet'),
  compatibility('candlestick', 'candlestick'),
  compatibility('cci', 'commodity-channel-index'),
  compatibility('chaikin', 'chaikin-oscillator'),
  compatibility('cmf', 'chaikin-money-flow'),
  compatibility('cmo', 'chande-momentum-oscillator'),
  compatibility('column', 'column'),
  compatibility('columnpyramid', 'column-pyramid'),
  compatibility('columnrange', 'column-range'),
  compatibility('contour', 'contour'),
  compatibility('cylinder', 'cylinder'),
  compatibility('dema', 'double-exponential-average'),
  compatibility('dependencywheel', 'dependency-wheel'),
  compatibility('disparityindex', 'disparity-index'),
  compatibility('dmi', 'directional-movement-index'),
  compatibility('dpo', 'detrended-price-oscillator'),
  compatibility('dumbbell', 'dumbbell'),
  compatibility('ema', 'exponential-moving-average'),
  compatibility('errorbar', 'error-bar'),
  compatibility('flags', 'event-flags'),
  compatibility('flowmap', 'flow-map'),
  compatibility('funnel', 'funnel'),
  compatibility('funnel3d', 'funnel-3d'),
  compatibility('gantt', 'gantt'),
  compatibility('gauge', 'gauge'),
  compatibility('geoheatmap', 'geo-heatmap'),
  compatibility('heatmap', 'heatmap'),
  compatibility('heikinashi', 'heikin-ashi'),
  compatibility('histogram', 'histogram'),
  compatibility('hlc', 'high-low-close'),
  compatibility('hollowcandlestick', 'hollow-candlestick'),
  compatibility('ikh', 'ichimoku-cloud'),
  compatibility('item', 'item'),
  compatibility('keltnerchannels', 'keltner-channels'),
  compatibility('klinger', 'klinger-oscillator'),
  compatibility('line', 'line'),
  compatibility('linearregression', 'linear-regression'),
  compatibility('linearregressionangle', 'linear-regression-angle'),
  compatibility('linearregressionintercept', 'linear-regression-intercept'),
  compatibility('linearregressionslope', 'linear-regression-slope'),
  compatibility('lollipop', 'lollipop'),
  compatibility('macd', 'moving-average-convergence-divergence'),
  compatibility('map', 'map'),
  compatibility('mapbubble', 'map-bubble'),
  compatibility('mapline', 'map-line'),
  compatibility('mappoint', 'map-point'),
  compatibility('mfi', 'money-flow-index'),
  compatibility('momentum', 'momentum'),
  compatibility('natr', 'normalized-average-true-range'),
  compatibility('networkgraph', 'network-graph'),
  compatibility('obv', 'on-balance-volume'),
  compatibility('ohlc', 'open-high-low-close'),
  compatibility('organization', 'organization-network'),
  compatibility('packedbubble', 'packed-bubble'),
  compatibility('pareto', 'pareto'),
  compatibility('pc', 'price-channel'),
  compatibility('pictorial', 'pictorial-column'),
  compatibility('pie', 'pie'),
  compatibility('pivotpoints', 'pivot-points'),
  compatibility('pointandfigure', 'point-and-figure'),
  compatibility('polygon', 'polygon'),
  compatibility('ppo', 'percentage-price-oscillator'),
  compatibility('priceenvelopes', 'price-envelopes'),
  compatibility('psar', 'parabolic-stop-and-reverse'),
  compatibility('pyramid', 'pyramid'),
  compatibility('pyramid3d', 'pyramid-3d'),
  compatibility('renko', 'renko'),
  compatibility('roc', 'rate-of-change'),
  compatibility('rsi', 'relative-strength-index'),
  compatibility('sankey', 'sankey'),
  compatibility('scatter', 'scatter'),
  compatibility('scatter3d', 'scatter-3d'),
  compatibility('slowstochastic', 'slow-stochastic'),
  compatibility('sma', 'simple-moving-average'),
  compatibility('solidgauge', 'solid-gauge'),
  compatibility('spline', 'spline'),
  compatibility('stochastic', 'stochastic'),
  compatibility('streamgraph', 'streamgraph'),
  compatibility('sunburst', 'sunburst'),
  compatibility('supertrend', 'supertrend'),
  compatibility('tema', 'triple-exponential-average'),
  compatibility('tiledwebmap', 'tiled-map'),
  compatibility('tilemap', 'tile-map'),
  compatibility('timeline', 'timeline'),
  compatibility('treegraph', 'tree-graph'),
  compatibility('treemap', 'treemap'),
  compatibility('trendline', 'trendline'),
  compatibility('trix', 'triple-exponential-oscillator'),
  compatibility('variablepie', 'variable-pie'),
  compatibility('variwide', 'variable-width'),
  compatibility('vbp', 'volume-by-price'),
  compatibility('vector', 'vector'),
  compatibility('venn', 'venn'),
  compatibility('vwap', 'volume-weighted-average-price'),
  compatibility('waterfall', 'waterfall'),
  compatibility('williamsr', 'williams-range'),
  compatibility('windbarb', 'wind-barb'),
  compatibility('wma', 'weighted-moving-average'),
  compatibility('wordcloud', 'word-cloud'),
  compatibility('xrange', 'x-range'),
  compatibility('zigzag', 'zigzag'),
] as const;

export const seriesCompatibilityIds = seriesCompatibilityCatalog.map(
  ({ identifier }) => identifier,
);

const compatibilityByIdentifier = new Map(
  seriesCompatibilityCatalog.map((item) => [item.identifier, item]),
);

export function resolveSeriesType(identifier: string): SeriesCompatibilityEntry | undefined {
  const normalized = identifier
    .trim()
    .toLowerCase()
    .replaceAll(/[^a-z0-9]/g, '');
  return compatibilityByIdentifier.get(normalized);
}
