import type { ThemeTokens } from './types.js';

const palette = [
  '#4f46e5',
  '#0f9f8a',
  '#f59e0b',
  '#e05260',
  '#7c3aed',
  '#0e7490',
  '#db2777',
  '#65a30d',
  '#475569',
  '#ea580c',
] as const;

const pointToCssPixel = 96 / 72;
const millimeterToCssPixel = 96 / 25.4;

export const graflumeLight: ThemeTokens = {
  name: 'graflume-light',
  mode: 'light',
  colors: {
    background: '#ffffff',
    surface: '#f8fafc',
    text: '#0f172a',
    mutedText: '#64748b',
    axis: '#cbd5e1',
    grid: '#e8eef6',
    focus: '#4f46e5',
    palette,
    sequential: ['#eef2ff', '#c7d2fe', '#818cf8', '#4f46e5', '#312e81'],
    diverging: ['#b42318', '#f79084', '#f8fafc', '#84adff', '#3448c5'],
  },
  typography: {
    fontFamily:
      'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: 12,
    titleSize: 20,
    subtitleSize: 12,
    lineHeight: 1.45,
  },
  spacing: { xs: 4, sm: 8, md: 12, lg: 16, xl: 24 },
  axis: { lineWidth: 1, tickLength: 0, labelPadding: 9, gridLineWidth: 1 },
  mark: { lineWidth: 2.5, pointRadius: 4.5, barRadius: 5, opacity: 1 },
  motion: { duration: 280, easing: 'ease-out' },
};

export const graflumeDark: ThemeTokens = {
  ...graflumeLight,
  name: 'graflume-dark',
  mode: 'dark',
  colors: {
    ...graflumeLight.colors,
    background: '#0b1020',
    surface: '#111827',
    text: '#f8fafc',
    mutedText: '#a7b2c5',
    axis: '#475569',
    grid: '#25314a',
    focus: '#818cf8',
    palette: [
      '#818cf8',
      '#2dd4bf',
      '#fbbf24',
      '#fb7185',
      '#a78bfa',
      '#22d3ee',
      '#f472b6',
      '#a3e635',
      '#94a3b8',
      '#fb923c',
    ],
    sequential: ['#1e293b', '#3730a3', '#6366f1', '#a5b4fc', '#eef2ff'],
    diverging: ['#fb7185', '#be123c', '#334155', '#4f46e5', '#a5b4fc'],
  },
};

/**
 * ggplot2 v4.0.3 theme_gray() rendered in CSS pixels at the browser reference
 * density of 96 dpi. Data-scale colours follow ggplot2's default hue and
 * two-colour continuous scales rather than a fixed categorical array.
 */
export const graflumeGgplot: ThemeTokens = {
  name: 'ggplot',
  mode: 'light',
  colors: {
    background: '#FFFFFF',
    surface: '#FFFFFF',
    panel: '#EBEBEB',
    text: '#000000',
    mutedText: '#4D4D4D',
    subtitle: '#000000',
    axisTitle: '#000000',
    axis: '#333333',
    grid: '#FFFFFF',
    minorGrid: '#FFFFFF',
    focus: '#3366FF',
    palette: [
      '#F8766D',
      '#D89000',
      '#A3A500',
      '#39B600',
      '#00BF7D',
      '#00BFC4',
      '#00B0F6',
      '#9590FF',
      '#E76BF3',
      '#FF62BC',
    ],
    paletteMode: 'ggplot2-hue',
    sequential: ['#132B43', '#56B1F7'],
    diverging: ['#832424', '#FFFFFF', '#3A3A98'],
  },
  typography: {
    fontFamily: 'sans-serif',
    fontSize: 11 * pointToCssPixel,
    fontWeight: 400,
    titleSize: 13.2 * pointToCssPixel,
    titleWeight: 400,
    subtitleSize: 11 * pointToCssPixel,
    subtitleWeight: 400,
    axisLabelSize: 8.8 * pointToCssPixel,
    axisLabelWeight: 400,
    axisTitleSize: 11 * pointToCssPixel,
    axisTitleWeight: 400,
    legendLabelSize: 8.8 * pointToCssPixel,
    legendLabelWeight: 400,
    legendTitleSize: 11 * pointToCssPixel,
    legendTitleWeight: 400,
    titlePosition: 'panel',
    lineHeight: 0.9,
  },
  spacing: {
    xs: 5.5 * pointToCssPixel,
    sm: 5.5 * pointToCssPixel,
    md: 11 * pointToCssPixel,
    lg: 5.5 * pointToCssPixel,
    xl: 22 * pointToCssPixel,
    plotMargin: 5.5 * pointToCssPixel,
  },
  axis: {
    lineWidth: 0.5 * millimeterToCssPixel,
    tickLength: 2.75 * pointToCssPixel,
    labelPadding: 2.2 * pointToCssPixel,
    gridLineWidth: 0.5 * millimeterToCssPixel,
    lineVisible: false,
    ticksVisible: true,
    gridX: true,
    gridX2: false,
    gridY: true,
    gridY2: false,
    gridOpacity: 1,
    minorGridVisible: true,
    minorGridLineWidth: 0.25 * millimeterToCssPixel,
    minorGridOpacity: 1,
    emphasizeZero: false,
    lineCap: 'butt',
    titleGap: 2.75 * pointToCssPixel,
  },
  mark: {
    lineWidth: 0.5 * millimeterToCssPixel,
    pointRadius: 0.75 * millimeterToCssPixel,
    barRadius: 0,
    opacity: 1,
    defaultColor: '#000000',
    lineColor: '#000000',
    pointFill: '#000000',
    pointStroke: '#000000',
    pointStrokeWidth: 0.5 * millimeterToCssPixel,
    barFill: '#595959',
    barWidthRatio: 0.9,
    areaFill: '#333333',
    areaStrokeVisible: false,
    lineCap: 'butt',
    lineJoin: 'round',
  },
  legend: {
    surfaceOpacity: 1,
    borderWidth: 0,
    cornerRadius: 0,
    swatchRadius: 0,
    swatchSize: 1.2 * 11 * pointToCssPixel,
    lineWidth: 0.5 * millimeterToCssPixel,
    pointRadius: 0.75 * millimeterToCssPixel,
    pointStrokeWidth: 0.5 * millimeterToCssPixel,
    lineCap: 'butt',
  },
  motion: { duration: 280, easing: 'ease-out' },
};
