import type { ThemeTokens } from './types.js';

const palette = [
  '#4f46e5',
  '#0f9f8a',
  '#f59e0b',
  '#e05260',
  '#7c3aed',
  '#0e7490',
  '#db2777',
  '#65a30d',
  '#475569',
  '#ea580c',
] as const;

const pointToCssPixel = 96 / 72;
const millimeterToCssPixel = 96 / 25.4;
const matplotlibPointToCssPixel = 100 / 72;

const matplotlibPalette = [
  '#1F77B4',
  '#FF7F0E',
  '#2CA02C',
  '#D62728',
  '#9467BD',
  '#8C564B',
  '#E377C2',
  '#7F7F7F',
  '#BCBD22',
  '#17BECF',
] as const;

export const graflumeLight: ThemeTokens = {
  name: 'graflume-light',
  mode: 'light',
  colors: {
    background: '#ffffff',
    surface: '#f8fafc',
    text: '#0f172a',
    mutedText: '#64748b',
    axis: '#cbd5e1',
    grid: '#e8eef6',
    focus: '#4f46e5',
    palette,
    sequential: ['#eef2ff', '#c7d2fe', '#818cf8', '#4f46e5', '#312e81'],
    diverging: ['#b42318', '#f79084', '#f8fafc', '#84adff', '#3448c5'],
  },
  typography: {
    fontFamily:
      'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: 12,
    titleSize: 20,
    subtitleSize: 12,
    lineHeight: 1.45,
  },
  spacing: { xs: 4, sm: 8, md: 12, lg: 16, xl: 24 },
  axis: { lineWidth: 1, tickLength: 0, labelPadding: 9, gridLineWidth: 1 },
  mark: { lineWidth: 2.5, pointRadius: 4.5, barRadius: 5, opacity: 1 },
  motion: { duration: 280, easing: 'ease-out' },
};

export const graflumeDark: ThemeTokens = {
  ...graflumeLight,
  name: 'graflume-dark',
  mode: 'dark',
  colors: {
    ...graflumeLight.colors,
    background: '#0b1020',
    surface: '#111827',
    text: '#f8fafc',
    mutedText: '#a7b2c5',
    axis: '#475569',
    grid: '#25314a',
    focus: '#818cf8',
    palette: [
      '#818cf8',
      '#2dd4bf',
      '#fbbf24',
      '#fb7185',
      '#a78bfa',
      '#22d3ee',
      '#f472b6',
      '#a3e635',
      '#94a3b8',
      '#fb923c',
    ],
    sequential: ['#1e293b', '#3730a3', '#6366f1', '#a5b4fc', '#eef2ff'],
    diverging: ['#fb7185', '#be123c', '#334155', '#4f46e5', '#a5b4fc'],
  },
};

/**
 * ggplot2 v4.0.3 theme_gray() rendered in CSS pixels at the browser reference
 * density of 96 dpi. Data-scale colours follow ggplot2's default hue and
 * two-colour continuous scales rather than a fixed categorical array.
 */
export const graflumeGgplot: ThemeTokens = {
  name: 'ggplot',
  mode: 'light',
  colors: {
    background: '#FFFFFF',
    surface: '#FFFFFF',
    panel: '#EBEBEB',
    text: '#000000',
    mutedText: '#4D4D4D',
    subtitle: '#000000',
    axisTitle: '#000000',
    axis: '#333333',
    grid: '#FFFFFF',
    minorGrid: '#FFFFFF',
    focus: '#3366FF',
    palette: [
      '#F8766D',
      '#D89000',
      '#A3A500',
      '#39B600',
      '#00BF7D',
      '#00BFC4',
      '#00B0F6',
      '#9590FF',
      '#E76BF3',
      '#FF62BC',
    ],
    paletteMode: 'ggplot2-hue',
    sequential: ['#132B43', '#56B1F7'],
    diverging: ['#832424', '#FFFFFF', '#3A3A98'],
  },
  typography: {
    fontFamily: 'sans-serif',
    fontSize: 11 * pointToCssPixel,
    fontWeight: 400,
    titleSize: 13.2 * pointToCssPixel,
    titleWeight: 400,
    subtitleSize: 11 * pointToCssPixel,
    subtitleWeight: 400,
    axisLabelSize: 8.8 * pointToCssPixel,
    axisLabelWeight: 400,
    axisTitleSize: 11 * pointToCssPixel,
    axisTitleWeight: 400,
    legendLabelSize: 8.8 * pointToCssPixel,
    legendLabelWeight: 400,
    legendTitleSize: 11 * pointToCssPixel,
    legendTitleWeight: 400,
    titlePosition: 'panel',
    lineHeight: 0.9,
  },
  spacing: {
    xs: 5.5 * pointToCssPixel,
    sm: 5.5 * pointToCssPixel,
    md: 11 * pointToCssPixel,
    lg: 5.5 * pointToCssPixel,
    xl: 22 * pointToCssPixel,
    plotMargin: 5.5 * pointToCssPixel,
  },
  axis: {
    lineWidth: 0.5 * millimeterToCssPixel,
    tickLength: 2.75 * pointToCssPixel,
    labelPadding: 2.2 * pointToCssPixel,
    gridLineWidth: 0.5 * millimeterToCssPixel,
    lineVisible: false,
    ticksVisible: true,
    gridX: true,
    gridX2: false,
    gridY: true,
    gridY2: false,
    gridOpacity: 1,
    minorGridVisible: true,
    minorGridLineWidth: 0.25 * millimeterToCssPixel,
    minorGridOpacity: 1,
    emphasizeZero: false,
    lineCap: 'butt',
    titleGap: 2.75 * pointToCssPixel,
  },
  mark: {
    lineWidth: 0.5 * millimeterToCssPixel,
    pointRadius: 0.75 * millimeterToCssPixel,
    barRadius: 0,
    opacity: 1,
    defaultColor: '#000000',
    lineColor: '#000000',
    pointFill: '#000000',
    pointStroke: '#000000',
    pointStrokeWidth: 0.5 * millimeterToCssPixel,
    barFill: '#595959',
    barWidthRatio: 0.9,
    areaFill: '#333333',
    areaStrokeVisible: false,
    lineCap: 'butt',
    lineJoin: 'round',
  },
  legend: {
    surfaceOpacity: 1,
    borderWidth: 0,
    cornerRadius: 0,
    swatchRadius: 0,
    swatchSize: 1.2 * 11 * pointToCssPixel,
    lineWidth: 0.5 * millimeterToCssPixel,
    pointRadius: 0.75 * millimeterToCssPixel,
    pointStrokeWidth: 0.5 * millimeterToCssPixel,
    lineCap: 'butt',
  },
  motion: { duration: 280, easing: 'ease-out' },
};

/**
 * R 4.6.1 base graphics defaults mapped to the browser reference density of
 * 96 dpi. Device-specific font discovery and rasterisation remain outside the
 * portable theme contract.
 */
export const graflumeRBase: ThemeTokens = {
  name: 'r-base',
  mode: 'light',
  colors: {
    background: '#FFFFFF',
    surface: '#FFFFFF',
    panel: '#FFFFFF',
    text: '#000000',
    mutedText: '#000000',
    subtitle: '#000000',
    axisTitle: '#000000',
    axis: '#000000',
    grid: '#D9D9D9',
    focus: '#2297E6',
    palette: [
      '#000000',
      '#DF536B',
      '#61D04F',
      '#2297E6',
      '#28E2E5',
      '#CD0BBC',
      '#F5C710',
      '#9E9E9E',
    ],
    sequential: ['#FFFFCC', '#FED976', '#FD8D3C', '#E31A1C', '#800026'],
    diverging: ['#2166AC', '#67A9CF', '#F7F7F7', '#EF8A62', '#B2182B'],
  },
  typography: {
    fontFamily: 'Helvetica, Arial, sans-serif',
    fontSize: 12 * pointToCssPixel,
    fontWeight: 400,
    titleSize: 14.4 * pointToCssPixel,
    titleWeight: 700,
    subtitleSize: 12 * pointToCssPixel,
    subtitleWeight: 400,
    axisLabelSize: 12 * pointToCssPixel,
    axisLabelWeight: 400,
    axisTitleSize: 12 * pointToCssPixel,
    axisTitleWeight: 400,
    legendLabelSize: 12 * pointToCssPixel,
    legendLabelWeight: 400,
    legendTitleSize: 12 * pointToCssPixel,
    legendTitleWeight: 400,
    titlePosition: 'panel',
    titleAlign: 'center',
    lineHeight: 1.2,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    plotPadding: { top: 24, right: 30, bottom: 73, left: 59 },
  },
  axis: {
    lineWidth: 1,
    boxVisible: true,
    boxLineWidth: 1,
    boxExcludedMarks: ['bar', 'pie'],
    tickLength: 6,
    labelPadding: 5,
    gridLineWidth: 1,
    lineVisible: true,
    ticksVisible: true,
    gridX: false,
    gridX2: false,
    gridY: false,
    gridY2: false,
    gridOpacity: 1,
    minorGridVisible: false,
    emphasizeZero: false,
    lineCap: 'butt',
    titleGap: 8,
  },
  mark: {
    lineWidth: 1,
    pointRadius: 3.75,
    barRadius: 0,
    opacity: 1,
    defaultColor: '#000000',
    lineColor: '#000000',
    pointFill: 'transparent',
    pointStroke: '#000000',
    pointStrokeWidth: 1,
    barFill: '#BEBEBE',
    barStroke: '#000000',
    barStrokeWidth: 1,
    barWidthRatio: 0.8,
    histogramFill: '#D3D3D3',
    boxplotFill: '#D3D3D3',
    boxplotLineWidth: 1,
    boxplotRadius: 0,
    piePalette: ['#FFFFFF', '#ADD8E6', '#FFE4E1', '#E0FFFF', '#E6E6FA', '#FFF8DC'],
    pieStroke: '#000000',
    pieStrokeWidth: 1,
    areaFill: '#BEBEBE',
    areaStroke: '#000000',
    areaStrokeVisible: true,
    lineCap: 'round',
    lineJoin: 'round',
  },
  legend: {
    surfaceOpacity: 1,
    borderWidth: 1,
    cornerRadius: 0,
    swatchRadius: 0,
    swatchSize: 12 * pointToCssPixel,
    lineWidth: 1,
    pointRadius: 3.75,
    pointStrokeWidth: 1,
    lineCap: 'round',
  },
  motion: { duration: 0, easing: 'linear' },
};

/**
 * Matplotlib 3.11.1's default rcParams mapped to a 640 x 480 browser canvas
 * at Matplotlib's default 100 dpi. Graflume retains its own chart semantics
 * while matching the reference typography, axes, marks, colour cycle, and
 * viridis/coolwarm scale surfaces.
 */
export const graflumeMatplotlib: ThemeTokens = {
  name: 'matplotlib',
  mode: 'light',
  colors: {
    background: '#FFFFFF',
    surface: '#FFFFFF',
    panel: '#FFFFFF',
    text: '#000000',
    mutedText: '#000000',
    subtitle: '#000000',
    axisTitle: '#000000',
    axis: '#000000',
    grid: '#B0B0B0',
    minorGrid: '#B0B0B0',
    focus: '#1F77B4',
    palette: matplotlibPalette,
    continuousInterpolation: 'step',
    sequential: [
      '#440154',
      '#440256',
      '#450457',
      '#450559',
      '#46075A',
      '#46085C',
      '#460A5D',
      '#460B5E',
      '#470D60',
      '#470E61',
      '#471063',
      '#471164',
      '#471365',
      '#481467',
      '#481668',
      '#481769',
      '#48186A',
      '#481A6C',
      '#481B6D',
      '#481C6E',
      '#481D6F',
      '#481F70',
      '#482071',
      '#482173',
      '#482374',
      '#482475',
      '#482576',
      '#482677',
      '#482878',
      '#482979',
      '#472A7A',
      '#472C7A',
      '#472D7B',
      '#472E7C',
      '#472F7D',
      '#46307E',
      '#46327E',
      '#46337F',
      '#463480',
      '#453581',
      '#453781',
      '#453882',
      '#443983',
      '#443A83',
      '#443B84',
      '#433D84',
      '#433E85',
      '#423F85',
      '#424086',
      '#424186',
      '#414287',
      '#414487',
      '#404588',
      '#404688',
      '#3F4788',
      '#3F4889',
      '#3E4989',
      '#3E4A89',
      '#3E4C8A',
      '#3D4D8A',
      '#3D4E8A',
      '#3C4F8A',
      '#3C508B',
      '#3B518B',
      '#3B528B',
      '#3A538B',
      '#3A548C',
      '#39558C',
      '#39568C',
      '#38588C',
      '#38598C',
      '#375A8C',
      '#375B8D',
      '#365C8D',
      '#365D8D',
      '#355E8D',
      '#355F8D',
      '#34608D',
      '#34618D',
      '#33628D',
      '#33638D',
      '#32648E',
      '#32658E',
      '#31668E',
      '#31678E',
      '#31688E',
      '#30698E',
      '#306A8E',
      '#2F6B8E',
      '#2F6C8E',
      '#2E6D8E',
      '#2E6E8E',
      '#2E6F8E',
      '#2D708E',
      '#2D718E',
      '#2C718E',
      '#2C728E',
      '#2C738E',
      '#2B748E',
      '#2B758E',
      '#2A768E',
      '#2A778E',
      '#2A788E',
      '#29798E',
      '#297A8E',
      '#297B8E',
      '#287C8E',
      '#287D8E',
      '#277E8E',
      '#277F8E',
      '#27808E',
      '#26818E',
      '#26828E',
      '#26828E',
      '#25838E',
      '#25848E',
      '#25858E',
      '#24868E',
      '#24878E',
      '#23888E',
      '#23898E',
      '#238A8D',
      '#228B8D',
      '#228C8D',
      '#228D8D',
      '#218E8D',
      '#218F8D',
      '#21908D',
      '#21918C',
      '#20928C',
      '#20928C',
      '#20938C',
      '#1F948C',
      '#1F958B',
      '#1F968B',
      '#1F978B',
      '#1F988B',
      '#1F998A',
      '#1F9A8A',
      '#1E9B8A',
      '#1E9C89',
      '#1E9D89',
      '#1F9E89',
      '#1F9F88',
      '#1FA088',
      '#1FA188',
      '#1FA187',
      '#1FA287',
      '#20A386',
      '#20A486',
      '#21A585',
      '#21A685',
      '#22A785',
      '#22A884',
      '#23A983',
      '#24AA83',
      '#25AB82',
      '#25AC82',
      '#26AD81',
      '#27AD81',
      '#28AE80',
      '#29AF7F',
      '#2AB07F',
      '#2CB17E',
      '#2DB27D',
      '#2EB37C',
      '#2FB47C',
      '#31B57B',
      '#32B67A',
      '#34B679',
      '#35B779',
      '#37B878',
      '#38B977',
      '#3ABA76',
      '#3BBB75',
      '#3DBC74',
      '#3FBC73',
      '#40BD72',
      '#42BE71',
      '#44BF70',
      '#46C06F',
      '#48C16E',
      '#4AC16D',
      '#4CC26C',
      '#4EC36B',
      '#50C46A',
      '#52C569',
      '#54C568',
      '#56C667',
      '#58C765',
      '#5AC864',
      '#5CC863',
      '#5EC962',
      '#60CA60',
      '#63CB5F',
      '#65CB5E',
      '#67CC5C',
      '#69CD5B',
      '#6CCD5A',
      '#6ECE58',
      '#70CF57',
      '#73D056',
      '#75D054',
      '#77D153',
      '#7AD151',
      '#7CD250',
      '#7FD34E',
      '#81D34D',
      '#84D44B',
      '#86D549',
      '#89D548',
      '#8BD646',
      '#8ED645',
      '#90D743',
      '#93D741',
      '#95D840',
      '#98D83E',
      '#9BD93C',
      '#9DD93B',
      '#A0DA39',
      '#A2DA37',
      '#A5DB36',
      '#A8DB34',
      '#AADC32',
      '#ADDC30',
      '#B0DD2F',
      '#B2DD2D',
      '#B5DE2B',
      '#B8DE29',
      '#BADE28',
      '#BDDF26',
      '#C0DF25',
      '#C2DF23',
      '#C5E021',
      '#C8E020',
      '#CAE11F',
      '#CDE11D',
      '#D0E11C',
      '#D2E21B',
      '#D5E21A',
      '#D8E219',
      '#DAE319',
      '#DDE318',
      '#DFE318',
      '#E2E418',
      '#E5E419',
      '#E7E419',
      '#EAE51A',
      '#ECE51B',
      '#EFE51C',
      '#F1E51D',
      '#F4E61E',
      '#F6E620',
      '#F8E621',
      '#FBE723',
      '#FDE725',
    ],
    diverging: [
      '#3B4CC0',
      '#5977E3',
      '#7B9FF9',
      '#9EBEFF',
      '#C0D4F5',
      '#DDDCDC',
      '#F2CBB7',
      '#F7AC8E',
      '#EE8468',
      '#D65244',
      '#B40426',
    ],
  },
  typography: {
    fontFamily:
      '"DejaVu Sans", "Bitstream Vera Sans", "Computer Modern Sans Serif", Arial, Helvetica, sans-serif',
    fontSize: 10 * matplotlibPointToCssPixel,
    fontWeight: 400,
    titleSize: 12 * matplotlibPointToCssPixel,
    titleWeight: 400,
    subtitleSize: 10 * matplotlibPointToCssPixel,
    subtitleWeight: 400,
    axisLabelSize: 10 * matplotlibPointToCssPixel,
    axisLabelWeight: 400,
    axisTitleSize: 10 * matplotlibPointToCssPixel,
    axisTitleWeight: 400,
    legendLabelSize: 10 * matplotlibPointToCssPixel,
    legendLabelWeight: 400,
    legendTitleSize: 10 * matplotlibPointToCssPixel,
    legendTitleWeight: 400,
    titlePosition: 'panel',
    titleAlign: 'center',
    lineHeight: 1.2,
  },
  spacing: {
    xs: 4 * matplotlibPointToCssPixel,
    sm: 8 * matplotlibPointToCssPixel,
    md: 12 * matplotlibPointToCssPixel,
    lg: 16 * matplotlibPointToCssPixel,
    xl: 24 * matplotlibPointToCssPixel,
    plotPadding: { top: 19, right: 64, bottom: 53, left: 80 },
    minimumTitleBlock: 12 * matplotlibPointToCssPixel + 16 * matplotlibPointToCssPixel,
  },
  axis: {
    lineWidth: 0.8 * matplotlibPointToCssPixel,
    boxVisible: true,
    boxLineWidth: 0.8 * matplotlibPointToCssPixel,
    boxExcludedMarks: ['pie'],
    tickLength: 3.5 * matplotlibPointToCssPixel,
    labelPadding: 3.5 * matplotlibPointToCssPixel,
    gridLineWidth: 0.8 * matplotlibPointToCssPixel,
    lineVisible: true,
    ticksVisible: true,
    gridX: false,
    gridX2: false,
    gridY: false,
    gridY2: false,
    gridOpacity: 1,
    minorGridVisible: false,
    emphasizeZero: false,
    lineCap: 'butt',
    titleGap: 4 * matplotlibPointToCssPixel,
  },
  mark: {
    lineWidth: 1.5 * matplotlibPointToCssPixel,
    pointRadius: 3 * matplotlibPointToCssPixel,
    pointStrokeWidth: 1 * matplotlibPointToCssPixel,
    pointColorMode: 'series',
    barRadius: 0,
    barStroke: 'transparent',
    barStrokeWidth: 0,
    barWidthRatio: 0.8,
    histogramGap: 0,
    boxplotFill: 'transparent',
    boxplotLineWidth: 1 * matplotlibPointToCssPixel,
    boxplotRadius: 0,
    boxplotMedianStroke: '#FF7F0E',
    piePalette: matplotlibPalette,
    pieStroke: 'transparent',
    pieStrokeWidth: 0,
    pieStartAngle: 0,
    pieDirection: 'counterclockwise',
    areaStroke: '#000000',
    areaStrokeVisible: false,
    areaColorMode: 'series',
    opacity: 1,
    lineCap: 'square',
    lineJoin: 'round',
  },
  legend: {
    surfaceOpacity: 0.8,
    borderWidth: 1 * matplotlibPointToCssPixel,
    borderColor: '#CCCCCC',
    cornerRadius: 4,
    swatchRadius: 0,
    swatchSize: 10 * matplotlibPointToCssPixel,
    lineWidth: 1.5 * matplotlibPointToCssPixel,
    pointRadius: 3 * matplotlibPointToCssPixel,
    pointStrokeWidth: 1 * matplotlibPointToCssPixel,
    lineCap: 'square',
    continuousSamples: 256,
  },
  motion: { duration: 0, easing: 'linear' },
};

type NeutralThemeDefinition = {
  readonly name: string;
  readonly mode: ThemeTokens['mode'];
  readonly colors: Partial<ThemeTokens['colors']>;
  readonly typography?: Partial<ThemeTokens['typography']>;
  readonly spacing?: Partial<ThemeTokens['spacing']>;
  readonly axis?: Partial<ThemeTokens['axis']>;
  readonly mark?: Partial<ThemeTokens['mark']>;
  readonly legend?: Partial<NonNullable<ThemeTokens['legend']>>;
  readonly motion?: Partial<ThemeTokens['motion']>;
};

const blueSequential = ['#eff6ff', '#bfdbfe', '#60a5fa', '#2563eb', '#1e3a8a'] as const;
const viridisSequential = ['#440154', '#3b528b', '#21918c', '#5ec962', '#fde725'] as const;
const warmSequential = ['#fff7ed', '#fed7aa', '#fb923c', '#c2410c', '#7c2d12'] as const;
const terrainSequential = ['#e0f2fe', '#7dd3fc', '#34d399', '#a3a341', '#7c5c3b'] as const;
const redBlueDiverging = ['#b91c1c', '#fca5a5', '#f8fafc', '#93c5fd', '#1d4ed8'] as const;
const darkDiverging = ['#ff5a5f', '#7f1d1d', '#111827', '#14532d', '#00d084'] as const;

/**
 * Neutral profiles share the portable theme shape without aliasing an existing
 * built-in. The definition contains only visual defaults; it never enables a
 * chart family, renderer, transform, or interaction capability.
 */
function createNeutralTheme(definition: NeutralThemeDefinition): ThemeTokens {
  const axisColor = definition.colors.axis ?? graflumeLight.colors.axis;
  return {
    name: definition.name,
    mode: definition.mode,
    colors: { ...graflumeLight.colors, ...definition.colors },
    typography: { ...graflumeLight.typography, ...definition.typography },
    spacing: { ...graflumeLight.spacing, ...definition.spacing },
    axis: { ...graflumeLight.axis, ...definition.axis },
    mark: { ...graflumeLight.mark, ...definition.mark },
    legend: {
      surfaceOpacity: definition.mode === 'dark' ? 0.94 : 1,
      borderWidth: 1,
      borderColor: axisColor,
      cornerRadius: definition.mark?.barRadius ?? 0,
      swatchRadius: definition.mark?.barRadius ?? 0,
      swatchSize: 12,
      lineWidth: definition.mark?.lineWidth ?? graflumeLight.mark.lineWidth,
      pointRadius: definition.mark?.pointRadius ?? graflumeLight.mark.pointRadius,
      pointStrokeWidth: 1,
      lineCap: definition.axis?.lineCap ?? 'round',
      continuousSamples: 64,
      ...definition.legend,
    },
    motion: { ...graflumeLight.motion, ...definition.motion },
  };
}

const neutralThemeDefinitions = [
  {
    name: 'editorial',
    mode: 'light',
    colors: {
      background: '#fbf8f1',
      surface: '#fffdf8',
      panel: '#fffdf8',
      text: '#26231f',
      mutedText: '#756d63',
      axis: '#8f867b',
      grid: '#ded7cb',
      focus: '#1f5a7a',
      palette: ['#1f3b5d', '#9f3a38', '#b07d2c', '#536b4a', '#76527a', '#447c87'],
      sequential: warmSequential,
      diverging: ['#9f3a38', '#df9b8f', '#fffdf8', '#91b2c2', '#1f5a7a'],
    },
    typography: {
      fontFamily: 'Georgia, "Times New Roman", serif',
      fontSize: 13,
      titleSize: 23,
      titleWeight: 700,
      subtitleSize: 13,
      titlePosition: 'plot',
      lineHeight: 1.55,
    },
    spacing: { xs: 5, sm: 9, md: 14, lg: 19, xl: 28 },
    axis: {
      lineWidth: 1,
      tickLength: 4,
      labelPadding: 8,
      gridLineWidth: 1,
      gridX: false,
      gridY: true,
      emphasizeZero: true,
    },
    mark: { lineWidth: 2, pointRadius: 4, barRadius: 0, opacity: 0.96 },
    legend: { borderWidth: 0, cornerRadius: 0, swatchRadius: 0 },
    motion: { duration: 180, easing: 'ease-out' },
  },
  {
    name: 'scientific-classic',
    mode: 'light',
    colors: {
      background: '#ffffff',
      surface: '#ffffff',
      panel: '#ffffff',
      text: '#111111',
      mutedText: '#4b5563',
      axis: '#111111',
      grid: '#d1d5db',
      focus: '#005f73',
      palette: ['#005f73', '#bb3e03', '#0a9396', '#9b2226', '#ca6702', '#3a0ca3'],
      sequential: viridisSequential,
      diverging: redBlueDiverging,
    },
    typography: {
      fontFamily: '"STIX Two Text", "Times New Roman", serif',
      fontSize: 12,
      titleSize: 17,
      titleWeight: 600,
      subtitleSize: 12,
      titleAlign: 'center',
      lineHeight: 1.35,
    },
    spacing: { xs: 4, sm: 7, md: 11, lg: 15, xl: 22 },
    axis: {
      lineWidth: 1.2,
      boxVisible: true,
      boxLineWidth: 1.2,
      tickLength: 5,
      labelPadding: 6,
      gridLineWidth: 0.75,
      gridX: false,
      gridY: false,
      emphasizeZero: false,
      lineCap: 'square',
    },
    mark: {
      lineWidth: 1.8,
      pointRadius: 3.5,
      barRadius: 0,
      opacity: 1,
      pointFill: 'transparent',
      pointStrokeWidth: 1.2,
      lineCap: 'square',
      lineJoin: 'miter',
    },
    legend: { cornerRadius: 0, swatchRadius: 0, borderColor: '#111111' },
    motion: { duration: 0, easing: 'linear' },
  },
  {
    name: 'statistical-minimal',
    mode: 'light',
    colors: {
      background: '#ffffff',
      surface: '#ffffff',
      panel: '#ffffff',
      text: '#172033',
      mutedText: '#667085',
      axis: '#98a2b3',
      grid: '#eaecf0',
      focus: '#2563eb',
      palette: ['#2563eb', '#dc2626', '#059669', '#7c3aed', '#d97706', '#0891b2'],
      sequential: blueSequential,
      diverging: redBlueDiverging,
    },
    typography: { fontSize: 12, titleSize: 18, subtitleSize: 12, lineHeight: 1.4 },
    spacing: { xs: 4, sm: 7, md: 11, lg: 15, xl: 21 },
    axis: {
      lineWidth: 1,
      tickLength: 0,
      labelPadding: 8,
      gridLineWidth: 1,
      lineVisible: false,
      ticksVisible: false,
      gridX: false,
      gridY: true,
      emphasizeZero: true,
    },
    mark: { lineWidth: 2.2, pointRadius: 4, barRadius: 1, opacity: 0.94 },
    legend: { borderWidth: 0, cornerRadius: 2, swatchRadius: 1 },
    motion: { duration: 160, easing: 'ease-out' },
  },
  {
    name: 'dashboard-dense',
    mode: 'light',
    colors: {
      background: '#f1f5f9',
      surface: '#ffffff',
      panel: '#ffffff',
      text: '#0f172a',
      mutedText: '#64748b',
      axis: '#94a3b8',
      grid: '#e2e8f0',
      focus: '#2563eb',
      palette: ['#2563eb', '#14b8a6', '#f59e0b', '#ef4444', '#8b5cf6', '#06b6d4'],
      sequential: blueSequential,
      diverging: ['#dc2626', '#fca5a5', '#ffffff', '#86efac', '#15803d'],
    },
    typography: { fontSize: 11, titleSize: 16, subtitleSize: 11, lineHeight: 1.25 },
    spacing: { xs: 3, sm: 5, md: 8, lg: 11, xl: 16 },
    axis: {
      lineWidth: 1,
      tickLength: 3,
      labelPadding: 5,
      gridLineWidth: 1,
      gridX: true,
      gridY: true,
      emphasizeZero: true,
    },
    mark: { lineWidth: 1.8, pointRadius: 3.5, barRadius: 2, opacity: 1 },
    legend: { cornerRadius: 4, swatchRadius: 2, swatchSize: 10 },
    motion: { duration: 120, easing: 'ease-out' },
  },
  {
    name: 'finance-terminal',
    mode: 'dark',
    colors: {
      background: '#070b0e',
      surface: '#0d1419',
      panel: '#0a1014',
      text: '#e6edf3',
      mutedText: '#8b949e',
      axis: '#3d4d57',
      grid: '#1c2a31',
      focus: '#f2cc60',
      palette: ['#00d084', '#ff5a5f', '#2f81f7', '#f2cc60', '#bc8cff', '#39c5cf'],
      sequential: ['#0d281f', '#075c40', '#00a36c', '#39d98a', '#b7f7d7'],
      diverging: darkDiverging,
    },
    typography: {
      fontFamily: '"IBM Plex Mono", "SFMono-Regular", Consolas, monospace',
      fontSize: 11,
      titleSize: 16,
      titleWeight: 600,
      subtitleSize: 11,
      lineHeight: 1.3,
    },
    spacing: { xs: 3, sm: 6, md: 9, lg: 12, xl: 18 },
    axis: {
      lineWidth: 1,
      tickLength: 4,
      labelPadding: 6,
      gridLineWidth: 1,
      gridX: true,
      gridY: true,
      emphasizeZero: true,
      lineCap: 'square',
    },
    mark: { lineWidth: 1.6, pointRadius: 3, barRadius: 0, opacity: 1, lineCap: 'square' },
    legend: { borderColor: '#3d4d57', cornerRadius: 0, swatchRadius: 0 },
    motion: { duration: 0, easing: 'linear' },
  },
  {
    name: 'observability',
    mode: 'dark',
    colors: {
      background: '#11131a',
      surface: '#191c26',
      panel: '#151822',
      text: '#dce3f0',
      mutedText: '#8f9bb3',
      axis: '#47516a',
      grid: '#293047',
      focus: '#7dcfff',
      palette: ['#7aa2f7', '#9ece6a', '#e0af68', '#f7768e', '#bb9af7', '#7dcfff'],
      sequential: ['#202544', '#344b8e', '#4f7ccf', '#7dcfff', '#c7f0ff'],
      diverging: ['#f7768e', '#9d3c5b', '#191c26', '#527a45', '#9ece6a'],
    },
    typography: { fontSize: 11, titleSize: 17, subtitleSize: 11, lineHeight: 1.35 },
    spacing: { xs: 3, sm: 6, md: 10, lg: 13, xl: 19 },
    axis: {
      lineWidth: 1,
      tickLength: 3,
      labelPadding: 6,
      gridLineWidth: 1,
      lineVisible: false,
      gridX: true,
      gridY: true,
      gridOpacity: 0.8,
      emphasizeZero: true,
    },
    mark: { lineWidth: 2, pointRadius: 3.5, barRadius: 2, opacity: 0.96 },
    legend: { borderColor: '#293047', cornerRadius: 4, swatchRadius: 2 },
    motion: { duration: 140, easing: 'ease-out' },
  },
  {
    name: 'geospatial',
    mode: 'light',
    colors: {
      background: '#eaf6fb',
      surface: '#f8fcfe',
      panel: '#f1f8f4',
      text: '#17324d',
      mutedText: '#5b7183',
      axis: '#7893a6',
      grid: '#d0e5ec',
      focus: '#0077b6',
      palette: ['#0077b6', '#2a9d8f', '#e9c46a', '#f4a261', '#e76f51', '#588157'],
      sequential: terrainSequential,
      diverging: ['#9b2226', '#ee9b8f', '#f8fcfe', '#94d2bd', '#005f73'],
    },
    typography: { fontSize: 12, titleSize: 19, subtitleSize: 12, lineHeight: 1.4 },
    spacing: { xs: 4, sm: 8, md: 12, lg: 16, xl: 24 },
    axis: {
      lineWidth: 1,
      tickLength: 3,
      labelPadding: 7,
      gridLineWidth: 0.8,
      gridX: true,
      gridY: true,
      gridOpacity: 0.75,
      emphasizeZero: false,
    },
    mark: { lineWidth: 1.8, pointRadius: 4, barRadius: 2, opacity: 0.92 },
    legend: { borderColor: '#b6d2dc', cornerRadius: 4, swatchRadius: 2 },
    motion: { duration: 220, easing: 'ease-in-out' },
  },
  {
    name: 'spatial-lab',
    mode: 'dark',
    colors: {
      background: '#050816',
      surface: '#0b1026',
      panel: '#080d20',
      text: '#edf4ff',
      mutedText: '#96a6c8',
      axis: '#41527a',
      grid: '#1a2850',
      focus: '#00e5ff',
      palette: ['#00e5ff', '#7c4dff', '#ff4081', '#76ff03', '#ffd740', '#ff6e40'],
      sequential: viridisSequential,
      diverging: ['#ff4081', '#7c4dff', '#101936', '#00b8d4', '#76ff03'],
    },
    typography: {
      fontFamily: '"IBM Plex Sans", Inter, ui-sans-serif, system-ui, sans-serif',
      fontSize: 12,
      titleSize: 18,
      subtitleSize: 12,
      lineHeight: 1.35,
    },
    spacing: { xs: 4, sm: 7, md: 11, lg: 15, xl: 22 },
    axis: {
      lineWidth: 1,
      tickLength: 4,
      labelPadding: 7,
      gridLineWidth: 0.8,
      gridX: true,
      gridY: true,
      gridOpacity: 0.8,
      emphasizeZero: false,
    },
    mark: { lineWidth: 1.8, pointRadius: 4, barRadius: 1, opacity: 0.92 },
    legend: { borderColor: '#41527a', cornerRadius: 2, swatchRadius: 1 },
    motion: { duration: 0, easing: 'linear' },
  },
  {
    name: 'presentation',
    mode: 'light',
    colors: {
      background: '#ffffff',
      surface: '#ffffff',
      panel: '#f8fafc',
      text: '#0f172a',
      mutedText: '#475569',
      axis: '#94a3b8',
      grid: '#e2e8f0',
      focus: '#1d4ed8',
      palette: ['#2563eb', '#e11d48', '#059669', '#f59e0b', '#7c3aed', '#0891b2'],
      sequential: blueSequential,
      diverging: redBlueDiverging,
    },
    typography: {
      fontSize: 14,
      titleSize: 26,
      titleWeight: 700,
      subtitleSize: 15,
      axisLabelSize: 13,
      axisTitleSize: 14,
      legendLabelSize: 13,
      legendTitleSize: 14,
      lineHeight: 1.5,
    },
    spacing: { xs: 6, sm: 10, md: 16, lg: 22, xl: 32 },
    axis: {
      lineWidth: 1.2,
      tickLength: 4,
      labelPadding: 10,
      gridLineWidth: 1,
      gridX: false,
      gridY: true,
      emphasizeZero: true,
    },
    mark: { lineWidth: 3, pointRadius: 5.5, barRadius: 6, opacity: 1 },
    legend: { borderWidth: 0, cornerRadius: 6, swatchRadius: 4, swatchSize: 15 },
    motion: { duration: 320, easing: 'ease-in-out' },
  },
  {
    name: 'pictorial',
    mode: 'light',
    colors: {
      background: '#fff9ed',
      surface: '#ffffff',
      panel: '#fffdf7',
      text: '#3b2f2f',
      mutedText: '#7c6860',
      axis: '#b39b8f',
      grid: '#f0dfd2',
      focus: '#e8590c',
      palette: ['#ff6b6b', '#4dabf7', '#ffd43b', '#69db7c', '#b197fc', '#ffa94d'],
      sequential: warmSequential,
      diverging: ['#f06595', '#ffa8c5', '#fff9ed', '#74c0fc', '#1971c2'],
    },
    typography: {
      fontFamily: '"Trebuchet MS", "Avenir Next", ui-sans-serif, sans-serif',
      fontSize: 13,
      titleSize: 22,
      titleWeight: 700,
      subtitleSize: 13,
      lineHeight: 1.45,
    },
    spacing: { xs: 5, sm: 9, md: 14, lg: 19, xl: 27 },
    axis: {
      lineWidth: 1.2,
      tickLength: 0,
      labelPadding: 9,
      gridLineWidth: 1,
      lineVisible: false,
      ticksVisible: false,
      gridX: false,
      gridY: true,
      emphasizeZero: false,
    },
    mark: { lineWidth: 3, pointRadius: 6, barRadius: 8, opacity: 0.96, lineCap: 'round' },
    legend: { borderColor: '#f0dfd2', cornerRadius: 8, swatchRadius: 6, swatchSize: 15 },
    motion: { duration: 360, easing: 'ease-in-out' },
  },
  {
    name: 'dark-technical',
    mode: 'dark',
    colors: {
      background: '#07111f',
      surface: '#0b1728',
      panel: '#091525',
      text: '#dbeafe',
      mutedText: '#8ba3bf',
      axis: '#35506d',
      grid: '#19324d',
      focus: '#22d3ee',
      palette: ['#22d3ee', '#a78bfa', '#fb7185', '#4ade80', '#facc15', '#60a5fa'],
      sequential: ['#082f49', '#075985', '#0284c7', '#22d3ee', '#cffafe'],
      diverging: ['#fb7185', '#9f1239', '#0b1728', '#0e7490', '#67e8f9'],
    },
    typography: {
      fontFamily: '"JetBrains Mono", "SFMono-Regular", Consolas, monospace',
      fontSize: 11,
      titleSize: 17,
      titleWeight: 600,
      subtitleSize: 11,
      lineHeight: 1.35,
    },
    spacing: { xs: 3, sm: 6, md: 10, lg: 14, xl: 20 },
    axis: {
      lineWidth: 1,
      tickLength: 4,
      labelPadding: 6,
      gridLineWidth: 1,
      gridX: true,
      gridY: true,
      gridOpacity: 0.9,
      emphasizeZero: true,
      lineCap: 'square',
    },
    mark: { lineWidth: 2, pointRadius: 3.5, barRadius: 0, opacity: 1, lineCap: 'square' },
    legend: { borderColor: '#35506d', cornerRadius: 0, swatchRadius: 0 },
    motion: { duration: 0, easing: 'linear' },
  },
  {
    name: 'high-contrast',
    mode: 'dark',
    colors: {
      background: '#000000',
      surface: '#000000',
      panel: '#000000',
      text: '#ffffff',
      mutedText: '#f5f5f5',
      axis: '#ffffff',
      grid: '#737373',
      focus: '#ffff00',
      palette: ['#ffff00', '#00ffff', '#ff00ff', '#00ff00', '#ff7f00', '#ffffff'],
      sequential: ['#000000', '#003cff', '#00ffff', '#ffff00', '#ffffff'],
      diverging: ['#ff00ff', '#ff7f00', '#000000', '#00ffff', '#ffffff'],
    },
    typography: {
      fontSize: 14,
      fontWeight: 600,
      titleSize: 24,
      titleWeight: 700,
      subtitleSize: 14,
      subtitleWeight: 600,
      axisLabelSize: 13,
      axisLabelWeight: 600,
      axisTitleSize: 14,
      axisTitleWeight: 700,
      legendLabelSize: 13,
      legendLabelWeight: 600,
      legendTitleSize: 14,
      legendTitleWeight: 700,
      lineHeight: 1.5,
    },
    spacing: { xs: 6, sm: 10, md: 15, lg: 20, xl: 28 },
    axis: {
      lineWidth: 2,
      boxVisible: true,
      boxLineWidth: 2,
      tickLength: 7,
      labelPadding: 9,
      gridLineWidth: 1.5,
      gridX: true,
      gridY: true,
      gridOpacity: 1,
      emphasizeZero: true,
      lineCap: 'square',
    },
    mark: {
      lineWidth: 3,
      pointRadius: 6,
      barRadius: 0,
      opacity: 1,
      pointStroke: '#000000',
      pointStrokeWidth: 2,
      lineCap: 'square',
      lineJoin: 'miter',
    },
    legend: {
      surfaceOpacity: 1,
      borderWidth: 2,
      borderColor: '#ffffff',
      cornerRadius: 0,
      swatchRadius: 0,
      swatchSize: 16,
      lineWidth: 3,
      pointRadius: 6,
      pointStrokeWidth: 2,
      lineCap: 'square',
    },
    motion: { duration: 0, easing: 'linear' },
  },
] as const satisfies readonly NeutralThemeDefinition[];

const neutralBuiltInThemes: readonly ThemeTokens[] = neutralThemeDefinitions.map((definition) =>
  createNeutralTheme(definition),
);

export interface BuiltInThemeCatalogEntry {
  readonly id: string;
  readonly tokens: ThemeTokens;
  readonly snapshot: boolean;
  readonly sourceBaseline?: string;
}

export const defaultThemeId = graflumeLight.name;

/** Ordered source of truth for every built-in theme and generated preview. */
export const builtInThemeCatalog: readonly BuiltInThemeCatalogEntry[] = [
  { id: graflumeLight.name, tokens: graflumeLight, snapshot: false },
  { id: graflumeDark.name, tokens: graflumeDark, snapshot: true },
  {
    id: graflumeGgplot.name,
    tokens: graflumeGgplot,
    snapshot: true,
    sourceBaseline: 'ggplot2 4.0.3',
  },
  {
    id: graflumeRBase.name,
    tokens: graflumeRBase,
    snapshot: true,
    sourceBaseline: 'R 4.6.1',
  },
  {
    id: graflumeMatplotlib.name,
    tokens: graflumeMatplotlib,
    snapshot: true,
    sourceBaseline: 'Matplotlib 3.11.1',
  },
  ...neutralBuiltInThemes.map((tokens) => ({ id: tokens.name, tokens, snapshot: true })),
];

export function builtInTheme(name: string): ThemeTokens | undefined {
  return builtInThemeCatalog.find((entry) => entry.id === name)?.tokens;
}
